disabled_rules:
  - identifier_name
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity

line_length: 
  warning: 250
  ignores_comments: true
  error: 500
  ignores_interpolated_strings: true
